//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainFare
    {
        public Nullable<int> TrainNo { get; set; }
        public int ACTier3_Fares { get; set; }
        public int ACTier2_Fares { get; set; }
        public int ACTier1_Fares { get; set; }
        public int SLFare { get; set; }
        public int SSFare { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
